// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HWills_Final_DMV.Models
{
    public partial class Car
    {
        public Car()
        {
            InfractLinks = new HashSet<InfractLink>();
        }

        public string CarId { get; set; }
        public string OperatorId { get; set; }
        public string CarPlateNum { get; set; }
        public string CarMake { get; set; }
        public string CarModel { get; set; }

        public virtual Operator Operator { get; set; }
        public virtual ICollection<InfractLink> InfractLinks { get; set; }
    }
}