// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HWills_Final_DMV.Models
{
    public partial class InfractLink
    {
        public string UserId { get; set; }
        public string OperatorId { get; set; }
        public string InfractId { get; set; }
        public string CarId { get; set; }

        public virtual Car Car { get; set; }
        public virtual Infract Infract { get; set; }
        public virtual Operator Operator { get; set; }
        public virtual User User { get; set; }
    }
}