// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HWills_Final_DMV.Models
{
    public partial class Infract
    {
        public Infract()
        {
            InfractLinks = new HashSet<InfractLink>();
        }

        public string InfractId { get; set; }
        public string InfractType { get; set; }

        public virtual ICollection<InfractLink> InfractLinks { get; set; }
    }
}